server:
  port: 8080

# Spring config
spring:
  # Connect to datasource
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/todo_list?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: html5
    servlet:
      content-type: text/html

mybatis:
  mapper-locations: classpath*:/mapping/*/*.xml
  type-aliases-package: com.wy.todo_backend.*.entity

logging:
  level:
    com.wy.gre_vocab.dao : debug
